---
# https://docs.mergify.com/
merge_queue:
  max_parallel_checks: 1

pull_request_rules:
  - name: default
    actions:
      queue:
    conditions: []

queue_rules:
  - name: default
    batch_size: 1
    merge_conditions: []
    merge_method: merge
    queue_conditions:
      - or:
          - author=JohnStrunk
          - author=renovate-bot
          - author=dependabot[bot]
          - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - check-success=Successful e2e tests
      - check-success=DCO
