---
# See: https://docs.codecov.io/docs/codecov-yaml
codecov:
  require_ci_to_pass: yes

coverage:
  precision: 1
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "diff,flags,files"
  behavior: default
  require_changes: yes
