---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 90
    script: |
      set -e

      echo "Waiting for snapshot"
      while [ -z "$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)" ]; do
        sleep 1
      done

      sname=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)

      echo "Verifying usage of custom snapshotclass"
      snapclass=$(kubectl -n "$NAMESPACE" get $sname -otemplate='{{.spec.volumeSnapshotClassName}}')
      echo "$snapclass" | grep -q 'my-custom-class'
