---
kind: Pod
apiVersion: v1
metadata:
  name: check-metrics
spec:
  containers:
    - name: workload
      image: fedora:latest
      command: ["sh", "-c"]
      args: ["curl --insecure https://snapscheduler-metrics.backube-snapscheduler.svc.cluster.local:8443/metrics | grep 'workqueue_work_duration_seconds_count{controller=\"snapshotschedule\",name=\"snapshotschedule\"}'"]
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsUser: 1000
        runAsGroup: 1000
        readOnlyRootFilesystem: true
  restartPolicy: OnFailure
  securityContext:
    runAsNonRoot: true
  terminationGracePeriodSeconds: 2
