package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
// Important: Run "operator-sdk generate k8s" to regenerate code after modifying this file
// Add custom validation using kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html

// SnapshotRetentionSpec defines how long snapshots should be kept.
// +k8s:openapi-gen=true
type SnapshotRetentionSpec struct {
	// Expires is the length of time (time.Duration) after which a given
	// Snapshot will be deleted.
	// +kubebuilder:validation:Pattern=^\d+(h|m|s)$
	Expires string `json:"expires,omitempty"`
	// +kubebuilder:validation:Minimum=1
	MaxCount *int32 `json:"maxCount,omitempty"`
}

// SnapshotTemplateHookSpec defines the execution hooks that should be invoked
// before and after taking a snapshot.
// +k8s:openapi-gen=true
type SnapshotTemplateHookSpec struct {
	PreSnapshot  string `json:"preSnapshot,omitempty"`
	PostSnapshot string `json:"postSnapshot,omitempty"`
}

// SnapshotTemplateSpec defines the template for Snapshot objects
// +k8s:openapi-gen=true
type SnapshotTemplateSpec struct {
	Labels map[string]string        `json:"labels,omitempty"`
	Hooks  SnapshotTemplateHookSpec `json:"hooks,omitempty"`
}

// SnapshotScheduleSpec defines the desired state of SnapshotSchedule
// +k8s:openapi-gen=true
type SnapshotScheduleSpec struct {
	// ClaimSelector selects which PVCs will be snapshotted according to
	// this schedule.
	ClaimSelector metav1.LabelSelector  `json:"claimSelector,omitempty"`
	Retention     SnapshotRetentionSpec `json:"retention,omitempty"`
	// Schedule is a Cronspec specifying when snapshots should be taken.
	// +kubebuilder:validation:Pattern=^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){5}$
	Schedule string `json:"schedule,omitempty"`
	// StartDeadlineSeconds is the maximum number of seconds after the
	// scheduled time when a snapshot is allowed to start.
	// +kubebuilder:validation:Minimum=1
	StartDeadlineSeconds *int32 `json:"startDeadlineSeconds,omitempty"`
	// Disabled determines whether this schedule is currently disabled.
	Disabled bool                 `json:"disabled,omitempty"`
	Template SnapshotTemplateSpec `json:"template,omitempty"`
}

// SnapshotScheduleStatus defines the observed state of SnapshotSchedule
// +k8s:openapi-gen=true
type SnapshotScheduleStatus struct {
	// LastSnapshotTime is the time of the most recent set of snapshots
	// generated by this schedule.
	LastSnapshotTime string `json:"lastSnapshotTime,omitempty"`
	// LastSnapshotResult is the result of the last attempted set of
	// snapshots.
	LastSnapshotResult string `json:"lastSnapshotResult,omitempty"`
	// NextSnapshotTime is the time when this schedule should create the
	// next set of snapshots.
	NextSnapshotTime string `json:"nextSnapshotTime,omitempty"`
}

// SnapshotSchedule is the Schema for the snapshotschedules API
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
type SnapshotSchedule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   SnapshotScheduleSpec   `json:"spec,omitempty"`
	Status SnapshotScheduleStatus `json:"status,omitempty"`
}

// SnapshotScheduleList contains a list of SnapshotSchedule
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type SnapshotScheduleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SnapshotSchedule `json:"items"`
}

func init() {
	SchemeBuilder.Register(&SnapshotSchedule{}, &SnapshotScheduleList{})
}
