// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"./pkg/apis/snapscheduler/v1alpha1.SnapshotSchedule":       schema_pkg_apis_snapscheduler_v1alpha1_SnapshotSchedule(ref),
		"./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleSpec":   schema_pkg_apis_snapscheduler_v1alpha1_SnapshotScheduleSpec(ref),
		"./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleStatus": schema_pkg_apis_snapscheduler_v1alpha1_SnapshotScheduleStatus(ref),
	}
}

func schema_pkg_apis_snapscheduler_v1alpha1_SnapshotSchedule(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SnapshotSchedule is the Schema for the snapshotschedules API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleSpec", "./pkg/apis/snapscheduler/v1alpha1.SnapshotScheduleStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_snapscheduler_v1alpha1_SnapshotScheduleSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SnapshotScheduleSpec defines the desired state of SnapshotSchedule",
				Type:        []string{"object"},
			},
		},
	}
}

func schema_pkg_apis_snapscheduler_v1alpha1_SnapshotScheduleStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "SnapshotScheduleStatus defines the observed state of SnapshotSchedule",
				Type:        []string{"object"},
			},
		},
	}
}
