---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 90
    script: |
      set -e

      echo "Waiting for snapshot"
      while true; do
        snapshots=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)
        [ -n "$snapshots" ] && break
        sleep 1
      done

      sname=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)

      echo "Verifying correct PVC was snapshotted"
      echo "$sname" | grep -q "voldata"
      echo "Verifying there is only 1 snapshot"
      echo "$sname"
      [ "$(echo "$sname" | wc -l)" -eq 1 ]
