---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 180
    script: |
      set -e

      for n in datavol voldata; do
        echo "Waiting for snapshot of $n"
        while true; do
          snapshots=$(kubectl -n "$NAMESPACE" get volumesnapshots -oname)
          [ -n "$snapshots" ] && break
          sleep 1
        done
      done
