---
apiVersion: kuttl.dev/v1beta1
kind: TestStep
commands:
  - timeout: 180
    script: |
      set -e -o pipefail

      for n in datavol voldata; do
        echo "Waiting for snapshot of $n"
        while [ "$(kubectl -n "$NAMESPACE" get volumesnapshots -oname | wc -l)" -lt 1 ]; do
          sleep 1
        done
      done
